<?php
/**
 * @file
 * Logic for the module functionality.
 */

/**
 * Implements hook_menu().
 */
function wtf_block_menu() {
  $items['admin/config/administration/wtf'] = array(
    'title' => 'WTF Block Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wtf_block_config_form'),
    'access arguments' => array('administer wtf_block'),
    'file' => 'wtf_block.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function wtf_block_permission() {
  return array(
    'administer wtf_block' => array(
      'title' => t('Administer WTF Block'),
      'description' => t('Configure WTF Block region settings. Warning: Give to trusted roles only; this permission has security implications.'),
    ),
  );
}

/**
 * Implements hook_block_list_alter().
 */
function wtf_block_block_list_alter(&$blocks) {
  global $theme_key;
  //Load configuration
  $current_config = variable_get('wtf_block_region');
  //Check if we have block transference enabled for this theme
  if (!empty($current_config['container_' . $theme_key]['region'])) {
    //Iterate over the blocks that are about to be rendered
    foreach ($blocks as $block) {
      //Skip the main content block or any other specified in the whitelist
      if ($block->delta != 'main' && empty($current_config['container_' . $theme_key]['whitelist']['blocks'][$block->bid])) {
        //Change region
        $block->region = $current_config['container_' . $theme_key]['region'];
      }
    }
  }
}
